id: AED1729BE
title: Pratyutpannabuddhasamādhisūtra
type: translation
pechas:
- I1B0F4428
- ID3132488
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-02-08 15:19:20.945200
  last_modified_at: 2023-02-08 15:19:20.945214
alignment_to_base:
  I1B0F4428/B804: E127
  ID3132488/D6DF: E127
